PATH_TO_DATA = "PATH_TO_YOUR_DATA"

BATCH_SIZE = 32
LEARNING_RATE = 0.001
MOMENTUM = 0.9
NUM_EPOCHS = 50

WEIGHT_DECAY = 1e-3

TRAIN_AUGMENTATION_TYPE = "basic"
VALID_AUGMENTATION_TYPE = None
