PATH_TO_DATA = "V:\ML\yandex-ml-2025\data"

BATCH_SIZE = 64
LEARNING_RATE = 0.001
MOMENTUM = 0.9
NUM_EPOCHS = 150

SCHEDULER = 'CosineAnnealingLR'

WEIGHT_DECAY = 1e-3

TRAIN_AUGMENTATION_TYPE = "basic"
VALID_AUGMENTATION_TYPE = None

MODEL = "PoseCNNv2"
# 21.4.25 14:00