PATH_TO_DATA = "V:\ML\yandex-ml-2025\data"

BATCH_SIZE = 32
LEARNING_RATE = 0.001
MOMENTUM = 0.9
NUM_EPOCHS = 50

WEIGHT_DECAY = 1e-5

TRAIN_AUGMENTATION_TYPE = "basic"
VALID_AUGMENTATION_TYPE = None

MODEL = "PoseCNNsc"