PATH_TO_DATA = "D:\\yandex-ml-2025\\data\\human_poses_data_reduced"

BATCH_SIZE = 8
LEARNING_RATE = 0.001
MOMENTUM = 0.9
NUM_EPOCHS = 1

WEIGHT_DECAY = 1e-3

TRAIN_AUGMENTATION_TYPE = "basic"
VALID_AUGMENTATION_TYPE = None
